name: Build and Release

permissions:
  contents: write


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 저장소 체크아웃
      uses: actions/checkout@v4

    - name: C++ 컴파일
      run: |
        mkdir -p build/cpp
        for file in cpp/*.cpp; do
          filename=$(basename "$file" .cpp)
          g++ "$file" -o "build/cpp/${filename}"
        done

    - name: Mono 설치 (C# 컴파일러)
      run: |
        sudo apt update
        sudo apt install -y mono-devel
      

    - name: C# 컴파일 (라이브러리 형태)
      run: |
        mkdir -p build/csharp
        for file in csharp/*.cs; do
          filename=$(basename "$file" .cs)
          mcs -target:library "$file" -out:"build/csharp/${filename}.dll"
        done
      

    - name: Kotlin 컴파일
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: kotlinc 설치
      run: |
        sudo apt-get update
        sudo apt-get install -y kotlin

    - name: Kotlin 빌드
      run: |
        mkdir -p build/kotlin
        for file in kotlin/*.kt; do
          filename=$(basename "$file" .kt)
          kotlinc "$file" -include-runtime -d "build/kotlin/${filename}.jar"
        done

    - name: 결과 압축
      run: |
        cd build
        zip -r compiled_artifacts.zip .

    - name: GitHub Release 생성
      uses: softprops/action-gh-release@v2
      with:
        name: "자동 릴리즈 - ${{ github.run_number }}"
        tag_name: "v${{ github.run_number }}"
        files: build/compiled_artifacts.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
